/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHead: typeof import('./inertia/components/AppHead.vue')['default']
    BarChart: typeof import('./inertia/components/ui/chart/BarChart.vue')['default']
    Button: typeof import('./inertia/components/ui/button/Button.vue')['default']
    DeleteModal: typeof import('./inertia/components/ui/deleteModal/DeleteModal.vue')['default']
    FormControl: typeof import('./inertia/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./inertia/components/ui/form/FormDescription.vue')['default']
    FormField: typeof import('./inertia/components/ui/form/FormField.vue')['default']
    FormItem: typeof import('./inertia/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./inertia/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./inertia/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./inertia/components/ui/input/Input.vue')['default']
    Label: typeof import('./inertia/components/ui/label/Label.vue')['default']
    PhoneModal: typeof import('./inertia/components/ui/phoneModal/PhoneModal.vue')['default']
    Table: typeof import('./inertia/components/ui/table/Table.vue')['default']
    TableBody: typeof import('./inertia/components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./inertia/components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./inertia/components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./inertia/components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./inertia/components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./inertia/components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./inertia/components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./inertia/components/ui/table/TableRow.vue')['default']
  }
}
